# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Y2uU+ju74Hp3b0sGQcRHtbeJhb3FGyZUV5Xf5H6WscujDo0OrkWiKE7M+orLb1r9fbcr7j/Bpe2THMvGMeRQ8u5gvl7yo2rHL0nVl3dNul9gB9iRMR/vAajOIMIrTC3+0vceKMM4w9PUdQXTdjvlmPCxiMwg+4/RMHYklBnAWlJp972q6G2shwc0o8ipU7KK5auAbcnSIsdvrvqoL3s2iGCXZjMF/cA0ChrmWqqTep+op/mdUm1+1Q+oGFuY80lCs2m4TckZLTzk7RkQeeSbyrNR/ibiAQdqmGC1vuB7HZyTZhIpo2MLEWM8LRY3nG+WEoiOILvObMXdeRNZFp0LEbkpxWoHxBwD/ZRVr7k0oUN/HINxbZkNnr9teIxdKSBTzIPnDSTqb2S9HxNIxn1rZ5zY8yGIG0yZla/y8Ic4yb6twgyB1LI5Xend0HqIKCAwEPYhwfhhRRtBYN6xpnpqQ0GYJOc4Ojqr/EwR0H8w86b9HqG73AZ6WD6bqkc4HVs883eZjFsLebK1rYQFRVOCwtCFGahn8YHdkzN/rzPK29AF00DV9lUEtUeZIZqPjnbfimhfPaTEljqj/1m6F9DOEno2Mo4RdcshVx7lffmzII1IZFiKtIdymPHlvdXYYfPdZbdJMVk0LsjQcOTwuGaZJaLTIw+iS2fsihW9S05nmOs="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
