travis:
  secure:
    BINSTAR_TOKEN: o8tqpEN+kf+pV/qFdG/yx/SRDTarU+NjLjjLkPns6Eef8GZSr3l0h9/AfJqD2/A8Cn7f84sEaTM1IN2mjGqiivqeWr0JM6eYZl8ch9ihJPmPmPGgPI7pFzHHgxu+aQG9M4W9kKvhfwRMuNSn9KNAiq430YNYMpxEe4rQYw4oCWaXxlg7ziGGj+WvzZGdsNAyCpvnZfs//PcRLz7WsWEFmicrgd8v1mxke37/GAK5tLYoTXceLVevYKoT3arIHDyFmib8E2cK435/4fuYdCa/nt+wGii58jBlao7yFqhTq98laDaOoZvBXLvs1rEGNCETt1m0MBeUq+7B7mjXwDnMV1pnmGMWRnxFooT8DePn/pvKYY8gGKMJmZLi2HlIkoNKNeYuu09w8wwQnVQGYnxQu0Hl/ENPkZzgluSShli1hcNI1j0JwhM7Ha4YFowU4QFQVvdWIiM72CKAopwQBqyLzPH225oSA/L11TM6bE00+ZNxIj5z60wSpROS9dR/72AY+Qwwowwpcv//dCJcjK5tMeXaYOoU4e86jTHQNneBdHSyw3t8V+3vpFPSeprZqIj5p7t4pZ4HBK54EAb9B3t1i6Tg12zguvX4454O4/p2aRimP6lWq1QIC7qyqEpvCQWtT9520qsCvXWrLb3zJfylBaAxfKxbb3Vlbs2nU43TnCY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
