travis:
  secure:
    BINSTAR_TOKEN: Y2uU+ju74Hp3b0sGQcRHtbeJhb3FGyZUV5Xf5H6WscujDo0OrkWiKE7M+orLb1r9fbcr7j/Bpe2THMvGMeRQ8u5gvl7yo2rHL0nVl3dNul9gB9iRMR/vAajOIMIrTC3+0vceKMM4w9PUdQXTdjvlmPCxiMwg+4/RMHYklBnAWlJp972q6G2shwc0o8ipU7KK5auAbcnSIsdvrvqoL3s2iGCXZjMF/cA0ChrmWqqTep+op/mdUm1+1Q+oGFuY80lCs2m4TckZLTzk7RkQeeSbyrNR/ibiAQdqmGC1vuB7HZyTZhIpo2MLEWM8LRY3nG+WEoiOILvObMXdeRNZFp0LEbkpxWoHxBwD/ZRVr7k0oUN/HINxbZkNnr9teIxdKSBTzIPnDSTqb2S9HxNIxn1rZ5zY8yGIG0yZla/y8Ic4yb6twgyB1LI5Xend0HqIKCAwEPYhwfhhRRtBYN6xpnpqQ0GYJOc4Ojqr/EwR0H8w86b9HqG73AZ6WD6bqkc4HVs883eZjFsLebK1rYQFRVOCwtCFGahn8YHdkzN/rzPK29AF00DV9lUEtUeZIZqPjnbfimhfPaTEljqj/1m6F9DOEno2Mo4RdcshVx7lffmzII1IZFiKtIdymPHlvdXYYfPdZbdJMVk0LsjQcOTwuGaZJaLTIw+iS2fsihW9S05nmOs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
