travis:
  secure:
    BINSTAR_TOKEN: AUU0ff3/nocofGgC8Pm5zYA9FdOJyjGzp038PWD2142URii/UU2gAHjhD+MfXJXFj/2OJTYADCF7uyLhzIWi9RynmUz2LpKM+Kqej6xDK6Bo0yJdUEkwcPbGLKgLeo9RCODZG62ap26pWDdV7mxYpoGGrQZdj61+pu4nkfRGHVzDfSai1Ih2+fPE7lkQqGQTM0VbLEBknjGlv8l9LyUFbmzIGapSOkKvHCE2M2fZrxBJwsXb8eoqp8w6I4lcFf50Bs2l6rOfB4KT8uZgunDcjPwMfglYsoIp9fngV3amp6gu0sTzB/UOTkef8zBiLuQlKuLwo92osZZqyJFWj9/WTiJ4zrv5zkz40m8T9gC5FsNUC/Wx4LdHCWRJOX7yjN92rVfh1EccwhGilyXwin6NTmYCb5DtWqf2yG/D0z7rKPWxMY0Q32tH34CXpucywiamIGUlwb+0dOCkbX0iGf3gzB3k0QYoYJmshXmMRzpcv2ktjzGW9vsC7roW9CCymZaHTXNiSS1TKJdSnKXIuYX/71Xb+U1t6BxERVOM9Z/kRc5e8yXH2Q3FCd3Nvx7SppBUD5SmzpOQo1nGY1g5G9KnbmRWGlOK2k6VBN5NEPBn2Qp02MwSna8Iwh2wt8OKp6RHrGZ+uYwoqZ3b+xO5kIQjzo5ZLR18CexkwpsrmpKQp0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
