travis:
  secure:
    BINSTAR_TOKEN: daFlz3tU/Glt02+tcijewTZ3Ihq4D1qB8jzd9ijz0WWOBmaEKSIsOe0+X0pB1O2UnpQlYcyQM8q99+7bGw0YhSmatyePA5iGLlbD0ZUUsOrWaxWfFHn/0KJGthA09FoNx0jAd+KBQ4/YM4xv3AJejqKe9nhn3TDTnpHiNnVXlp8w3fiZqkfOIosSGrtG553CjgEJBktZCLyQmihAI2V6FySPfZ20Q4CO9gEUA9WIw4SHJrl6ihkDjGcIPrKNTibRPj7lEcRpnFmoNBFK6mtuGZ61tbE3KXp1NcG4Uv+I2/AuBjB+6mqxVxGN71LxmRKuwCh3GkZwcRpULluQb4N82DJqNSGHtAnbfkVW0YFewGHrXxA2b0iz/R9OOt8CiWGZZ4JdyHhQIjZZAJJ8yVIo29eDEPpilynfyrbwpQFHhw52WZWnP2++soGrh8TpaLavcxRyc19x+Ymks6ouFjLqCL4eHB9eNUpJVdMkoCfB79dmnqi0IUv90UcUfiGC/XUBkPHI2hs96eOqLcKcqbjr1OqlzClJBzNf2gYrtDd81Q1lnUVJMVu4Pi/kKPrEtk9Y1LntOXoj/0qNUAdSyI32UTXTqySvUYMYnen2hIHMl1wnhSt4zubpkLj54hpVqzykz2uCZ+as6ZhbiVZrHkqkb4WWGdX6htfoBZxcalL81fw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
